first-active-range = [0, 10]
active-window-range = [0, 20]
min-stable-interval = 5

max-active-cells = 8

stabilise-results = false
skip-glancing = true
forbid-eater2 = true

pattern = '''
x = 19, y = 15, rule = LifeHistory
5.A$6.A$4.3A3$19B$19B$19B$19B$19B$19B$19B$19B$19B$19B!
'''
